CXX=g++
OBJS=singleton factory abstractFactory

all:$(OBJS)

singleton: singleton.cpp
	$(CXX) -o singleton singleton.cpp

factory: factory.cpp
	$(CXX) -o factory factory.cpp

abstractFactory: abstractFactory.cpp
	$(CXX) -o abstractFactory abstractFactory.cpp
